### ISSUE TITLE
Parse Args with Spaces

### ISSUE THREAD

**Issue by luthermonson** [rancher/wins#9] opened 2020-10-22 20:09 UTC
Per another issue in kubernetes-sigs/sig-windows-tools wins will parse the --args flag by a space which makes it impossible to pass in args with spaces e.g. --interface=Ethernet2 0.

gz#12873

**Comment by leflambeur** [comment] 2020-10-23 18:52
Credit to @rosskirkpat for the investigation on this

Currently Wins does not support space delimited parameters being added when bootstrapping kubernetes on windows

https://github.com/rancher/wins/blob/master/cmd/cmds/flags/list_value.go#L11-L13

This causes significant issues in AWS environments using multiple dns-suffixes as we currently query instance metadata for the hostname-override which then populates the kubelet start command with space delimited parameters.

Specifically if there is no cloud-provider-host-name-ovverride we will pull that information ourselves the instance metadata URL

https://github.com/rancher/rke-tools/blob/master/windows/cloud-provider.psm1#L190

Get-NodeOverridedName

created here:

https://github.com/rancher/rke-tools/blob/master/windows/cloud-provider.psm1#L241

called in the entrypoint and sidecar:

https://github.com/rancher/rke-tools/blob/master/windows/entrypoint.ps1#L116
https://github.com/rancher/rke-tools/blob/master/windows/sidecar.ps1#L81

For example:
` --hostname-override=ip-X-X-X-X.XXXXX.com gad.XXXXX.com apa.gad.XXXXX.com eur.gad.XXXXX.com gmea.gad.XXXXX.com nam.XXXXX.com us-east-1.compute.internal --feature-gates=HyperVContainer=true,WindowsGMSA=true `

They will see the following when adding windows nodes:
`10328 server.go:163] unknown command: apa.gad.XXXXX.com`

When it is passed through this:

https://github.com/rancher/rke-tools/blob/master/windows/entrypoint.ps1#L116

This means that in Windows AWS  environments with either proxies or other significant infrastructure considerations will always fail to build and this is significantly breaking

**Comment by anupama2501** [comment] 2021-04-01 16:54
On v2.5-b2a34d7cef440e3ed1de7d506233aa3a332649ae-head
Windows server 1909 SAC 
Docker 19.03.x EE 

Steps:
Bring up a custom cluster with Network provider flannel and Host gateway backend, amazon ec2 cloud provider[1 etcd,1cp, 1 linux worker node, 3 windows worker nodes]
Performed validation tests on the cluster 

steps have worked fine without any issues.

**Comment by anupama2501** [comment] 2021-04-02 21:42
Couldn't reproduce this issue on 2.5.5 and issue not seen on v2.5-b2a34d7cef440e3ed1de7d506233aa3a332649ae-head

Performed the following steps on 2.5.5 without any cloud provider:
1. Create a custom cluster with 1linux CP, 1 linux etcd, 2 worker windows 1909 
2. On the windows node before running the registration command pull the rke-tools provided by @luthermonson and tagged the pulled image
3. Run the registration command by appending the node-names flag as follows: --node-name \"test1 test2 test3\" on 1 node and --hostname-override=\“ip-X-X-X-X.XXXXX.com gad.XXXXX.com apa.gad.XXXXX.com\”  on the other node
4. The node comes up fine without any error

Cloud provider:
1. Create a custom cluster with 1linux CP, 1 linux etcd, 2 worker windows 1909 [with the required IAM profile selected in the AWS windows instance and required tags to the instance
2. In the custom cluster, select the network provider flannel and in-tree cloud provider amazon for the cluster
3. Perform the steps 2 through 4 from the without cloud-provider
4. Cluster comes up fine without any error 

Followed the same steps for with and without cloud provider for v2.5-b2a34d7cef440e3ed1de7d506233aa3a332649ae-head and the windows node comes up fine without any issue

**Comment by Jono-SUSE-Rancher** [comment] 2021-04-05 23:42
@luthermonson - Can you see if this is something that you are able to reproduce? And, if so, can you work with @anupama2501 to help re-create that for QA?

**Comment by sirredbeard** [comment] 2021-04-16 20:14
The original issue was fixed via PowerShell.

Support for parsing lists containing spaces using escape quotes was added. https://github.com/rancher/wins/pull/17

A proper integration test has been approved, waiting to be merged. https://github.com/rancher/wins/pull/30

Otherwise, our team is unable to reproduce the issue.

I propose closing this issue.

**Closed** 2021-04-19 22:39 UTC
Labels: QA/M, QA/need-info, [zube]: To Test, priority/2, status/resolved
